sudo: required

services:
  - docker

before_install:
  - docker build -t image .
  - docker run -d image
  - docker ps -a

script:
  - docker run -it --rm image composer --version
  - docker run -it --rm image nano --version
  - docker run -it --rm image php --version
  - docker run -it --rm image php -m
  - docker run -it --rm image vim --version
