sudo: required

services:
  - docker

before_install:
  - docker build -t image .
  - docker run -d image
  - docker ps -a

script:
  - docker run -it --rm image composer --version
  - docker run -it --rm image bower --version
  - docker run -it --rm image grunt --version
  - docker run -it --rm image gulp --version
  - docker run -it --rm image mysql --version
  - docker run -it --rm image node --version
  - docker run -it --rm image npm --version
  - docker run -it --rm image nano --version
  - docker run -it --rm image php --version
  - docker run -it --rm image php -m
  - docker run -it --rm image python3 --version
  - docker run -it --rm image vim --version
  - docker run -it --rm image yarn --version
