sudo: required

services:
  - docker

before_install:
  - docker build -t image .
  - docker run -d image
  - docker ps -a

script:
  - docker run -it --rm image composer --version
  - docker run -it --rm image phpunit --version
